# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Vatsala Dorairajan
tagline:             'Permanently Curious'
description:         "This site is built using a <a href='http://jekyllrb.com' target='_blank'>Jekyll</a> theme. Theme built by <a href='https://twitter.com/mdo' target='_blank'>@mdo</a> and customised by <a href='https://twitter.com/vatsala' target='_blank'>@vatsala</a>"
url:                 http://vatsala.co.in
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Vatsala Dorairajan
  url:               http://vatsala.co.in
  email:             vatsala<dot>dorairajan@gmail.com
  twitter:           htts://twitter.com/vatsala

# Custom vars
version:             1.0.0
